# Schema for the configuration files of the Siteimprove module.
siteimprove.settings:
  type: config_object
  label: 'Siteimprove settings'
  mapping:
    token:
      type: string
      label: 'Siteimprove Plugin token'
    domain_plugin_id:
      type: text
      label: 'Siteimprove plugin used'
siteimprove.domain.single.settings:
  type: config_object
  label: 'Siteimprove Single Domain settings'
  mapping:
    domain:
      type: text
      label: 'Frontend domain name (no protocol, no trailing slash)'
