# Schema for the configuration files of the Siteimprove module.
siteimprove.settings:
  type: config_object
  label: 'Siteimprove settings'
  mapping:
    token:
      type: string
      label: 'Siteimprove Plugin token'
